FROM mdillon/postgis

RUN apt-get update && apt-get install -y wget

RUN mkdir -p /var/lib/postgresql/data/pgdata
ENV PGDATA=/var/lib/postgresql/data/pgdata
ENV POSTGRES_USER=pmsteps
ENV POSTGRES_DB=pmsteps
ENV POSTGRES_PASSWORD=pmsteps

RUN wget https://raw.githubusercontent.com/ruipgil/ProcessMySteps/master/schema.sql -O /docker-entrypoint-initdb.d/z_schema.sql
